const names = [
  "TAN CHIA CHUN",
  "TAN JIA MIN",
  "TAN WEI HUA",
  "WANG WENWEI",
  "WANG YIXIAN",
  "WANG YUWEI",
  "DARREN",
  "WEI YAQIN",
  "WONG MAYNARD",
  "ALOYSIUS",
  "WU QIYANG",
  "XU XIN",
  "XU ZIPENG",
  "YANG SHUOGENG",
  "YU HUI",
  "ZARIFAH BINTE ZULKIFLI",
  "ZHANG MENGTONG",
  "ZHANG YUN",
  "ZHAO WENDI",
  "ZHAO YUECHEN"
];

export default names;
